[tools]
age = "latest"
age-plugin-yubikey = "latest"
sops = "latest"

hadolint = "latest"
"github:terror/just-lsp" = "latest"
marksman = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
# "npm:bash-language-server" = "latest"
# "npm:yaml-language-server" = "latest"
