- name: docker.io/cloudflare/cloudflared
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/authelia/authelia
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/lldap/lldap
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+\-alpine$

- name: ghcr.io/hotio/caddy
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+$

- name: ghcr.io/hotio/jellyfin
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+$

- name: ghcr.io/hotio/jellyseerr
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+$

- name: ghcr.io/hotio/radarr
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+\.\d+$

- name: ghcr.io/hotio/sonarr
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+\.\d+$

- name: ghcr.io/hotio/prowlarr
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+\.\d+$

- name: ghcr.io/recyclarr/recyclarr
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/navidrome/navidrome
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/hotio/lidarr
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^pr\-plugins\-\d+\.\d+\.\d+\.\d+$

- name: ghcr.io/hotio/sabnzbd
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+$

- name: ghcr.io/hotio/qbittorrent
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+$

- name: ghcr.io/hotio/qbitmanage
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^release\-\d+\.\d+\.\d+$

- name: ghcr.io/immich-app/immich-server
  watch_repo: true
  sort_tags: reverse
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$

- name: ghcr.io/dani-garcia/vaultwarden
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+\-alpine$

- name: ghcr.io/gotify/server
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/crazy-max/diun
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/grafana/grafana
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/prom/prometheus
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$

- name: docker.io/prom/node-exporter
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$

- name: docker.io/prometheuscommunity/smartctl-exporter
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$

- name: gcr.io/cadvisor/cadvisor
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$

- name: ghcr.io/paperless-ngx/paperless-ngx
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/home-assistant/home-assistant
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/blakeblackshear/frigate
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/eclipse-mosquitto
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/creativeprojects/resticprofile
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: codeberg.org/forgejo/forgejo
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+\-rootless$

- name: code.forgejo.org/forgejo/runner
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/atuinsh/atuin
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

# note: too noisy
# - name: ghcr.io/searxng/searxng
#   watch_repo: true
#   max_tags: 3
#   sort_tags: semver
#   notify_on:
#     - new
#   include_tags:
#     - ^\d+\.\d+\.\d+\-[a-fA-F0-9]{9}$

- name: ghcr.io/kareadita/kavita
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: ghcr.io/slskd/slskd
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^\d+\.\d+\.\d+$

- name: docker.io/qmcgaw/gluetun
  watch_repo: true
  max_tags: 3
  sort_tags: semver
  notify_on:
    - new
  include_tags:
    - ^v\d+\.\d+\.\d+$
